### ISSUE TITLE
database initialization error

### ISSUE THREAD

**Issue by quanbrew** [moebooru/moebooru#101]
I had reproduce this bug in Ubuntu 16.04 and CentOS 6.9

```
[moebooru@moebooru live]$ bundle exec rake db:create
Created database 'moebooru_dev'
Created database 'moebooru_test'
[moebooru@moebooru live]$ bundle exec rake db:reset
Dropped database 'moebooru_dev'
Dropped database 'moebooru_test'
Created database 'moebooru_dev'
Created database 'moebooru_test'
psql:/home/moebooru/live/db/structure.sql:27: ERROR:  must be owner of extension plpgsql
rake aborted!
failed to execute:
psql -v ON_ERROR_STOP=1 -q -f /home/moebooru/live/db/structure.sql moebooru_dev

Please check the output above for any errors and make sure that `psql` is installed in your PATH and has proper permissions.

/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:structure:load
(See full trace by running task with --trace)
[moebooru@moebooru live]$ bundle exec rake db:migrate
== 1 AddPostLinks: migrating ==================================================
-- execute("ALTER TABLE posts ADD COLUMN next_post_id INTEGER REFERENCES posts ON DELETE SET NULL")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "posts" does not exist
: ALTER TABLE posts ADD COLUMN next_post_id INTEGER REFERENCES posts ON DELETE SET NULL
/home/moebooru/live/db/migrate/001_add_post_links.rb:3:in `up'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "posts" does not exist
: ALTER TABLE posts ADD COLUMN next_post_id INTEGER REFERENCES posts ON DELETE SET NULL
/home/moebooru/live/db/migrate/001_add_post_links.rb:3:in `up'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "posts" does not exist
/home/moebooru/live/db/migrate/001_add_post_links.rb:3:in `up'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/moebooru/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by nanaya** [comment]
Not sure when they added stop on error but for now you can remove the line 27 (`CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;`) and rerun `db:reset` (or `db:setup`). `db:migrate` isn't intended to be run from empty database.

**Comment by quanbrew** [comment]
@nanaya a workaround 
```
ALTER ROLE moebooru superuser;
```

**Comment by nanaya** [comment]
Should be fine now.
