### ISSUE TITLE
Doesn't start on Windows 10/mingw64

### ISSUE THREAD

**Issue by Kadantte** [moebooru/moebooru#119]
When I use those CMD's I get this Error:

```shell
Jae_Jin@DESKTOP-VEVU270 MINGW64 ~/Desktop/moebooru (master)
$ bundle exec rake db:reset
rake aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
C:/Users/Jae_Jin/Desktop/moebooru/config/environment.rb:5:in `<top (required)>'

Caused by:
Gem::LoadError: pg is not part of the bundle. Add it to your Gemfile.
C:/Users/Jae_Jin/Desktop/moebooru/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:reset => db:drop => db:load_config => environment
(See full trace by running task with --trace)
```

```shell
Jae_Jin@DESKTOP-VEVU270 MINGW64 ~/Desktop/moebooru (master)
$ bundle exec rake db:migrate
rake aborted!
LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.
C:/Users/Jae_Jin/Desktop/moebooru/config/environment.rb:5:in `<top (required)>'

Caused by:
Gem::LoadError: pg is not part of the bundle. Add it to your Gemfile.
C:/Users/Jae_Jin/Desktop/moebooru/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by nanaya** [comment]
In Gemfile file line 21 which says

```ruby
gem "pg", :platforms => [:ruby, :mingw]
```

Change it to

```ruby
gem "pg", :platforms => [:ruby, :mingw, :x64_mingw]
```

Note that support for Windows has always been questionable and I haven't tried it for a very long time. You might be better off using vagrant or Windows 10 WSL. I haven't tried either though - I usually do everything in Linux, etc (VM or otherwise).

**Comment by Kadantte** [comment]
Thank's for the help, I'll use moe on Linux since it's better this way.
