### ISSUE TITLE
bundle exec rake assets:precompile fails with "unexpected identifier" for "import babel"

### ISSUE THREAD

**Issue by ragibooru** [moebooru/moebooru#202]
```
/home/moe/booru/build.js:3
import babel from '@babel/core'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Ubuntu 20.04

```
$ nodejs --version
v10.19.0
```

```
$ npm --version
6.14.4
```

**Comment by ragibooru** [comment]
I used NVM to install the required NodeJS 16 and this works now. Closing.
