### ISSUE TITLE
Project warnings&errors

### ISSUE THREAD

**Issue by bloodev** [moebooru/moebooru#59]
I get this warning every time I boot up the server using unicorn, perhaps you know it, but just in case:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /var/www/test/config/environment.rb:5)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /var/www/test/config/environment.rb:5)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 5.1. (called from block in <top (required)> at /var/www/test/config/routes.rb:88)
```

I did a clean install last night while using a DB which is ~2months old and now I keep getting the same error on every request:

```
213.240.206.247 - - [07/Sep/2016:00:27:29 +0200] "GET / HTTP/1.1" 200 - 0.3964
E, [2016-09-07T00:27:29.004543 #10484] ERROR -- : app error: wrong number of arguments (given 2, expected 1) (ArgumentError)
E, [2016-09-07T00:27:29.004574 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/raindrops-0.17.0/lib/raindrops/middleware/proxy.rb:30:in `respond_to?'
E, [2016-09-07T00:27:29.004589 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/body_proxy.rb:14:in `respond_to?'
E, [2016-09-07T00:27:29.004600 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/lint.rb:735:in `each'
E, [2016-09-07T00:27:29.004619 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/body_proxy.rb:36:in `each'
E, [2016-09-07T00:27:29.004678 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/rack-2.0.1/lib/rack/chunked.rb:23:in `each'
E, [2016-09-07T00:27:29.004692 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_response.rb:57:in `http_response_write'
E, [2016-09-07T00:27:29.004705 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:573:in `process_client'
E, [2016-09-07T00:27:29.004716 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
E, [2016-09-07T00:27:29.004727 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/oob_gc.rb:70:in `process_client'
E, [2016-09-07T00:27:29.004739 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
E, [2016-09-07T00:27:29.004752 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
E, [2016-09-07T00:27:29.004763 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
E, [2016-09-07T00:27:29.004773 #10484] ERROR -- : /var/lib/gems/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
E, [2016-09-07T00:27:29.004785 #10484] ERROR -- : /usr/local/bin/unicorn:22:in `load'
E, [2016-09-07T00:27:29.004795 #10484] ERROR -- : /usr/local/bin/unicorn:22:in `<main>'
```

**Question:** 
By default the env is dev. I assume? I couldn't see in the option anywhere. I saw online I can change it to production by typing this:
`bin/rails db:environment:set RAILS_ENV=production`
Also, how saw that I need to run this in order to make it a deamon so I can close the SSH session
`bundle exec unicorn -p 80 -D`
prior that I was using `nohup bundle exec unicorn -p 80 &` but it did crash several times even thought I get virtually no visitors at all other than google.

**Comment by nanaya** [comment]
The unicorn error has been fixed (or more like removed). As for deprecation warnings, it'll be eventually cleared.
